server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: youshallnotpass
    sources:
      youtube: true
      soundcloud: true
      http: true
      twitch: true
    bufferDurationMs: 400
    frameBufferDurationMs: 1000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 1
    youtubeSearchEnabled: true
    resamplingQuality: HIGH
    gc-warnings: true
    opusEncodingQuality: 10

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
